name: Continuous Integration

on:
  push:
    branches:
      - main
      - '**'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    environment: qa 
    env:
      CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ vars.CYPRESS_API_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Start Docker container
        run: docker-compose up -d

      - name: Run Cypress tests
        run: npm run cypress:run:ci

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report